name: Run Tests for Kval (MacOS)

on:   
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]
        python-version: [ "3.9", "3.10", "3.11", "3.12"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Use the latest version of actions/checkout

    - name: Set up Python
      uses: actions/setup-python@v4  # Use the latest version of actions/setup-python
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -e '.[dev]'  # This installs the optional dev dependencies, including pytest

    - name: Run tests
      run: |
        pytest
      env:
        CI: true
